# -*- coding: utf-8 -*-
"""Recommend_food_final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16iQxAczdlaqlno25xW_TymIcg4WpoV6v
"""

!pip install pymysql

"""1. user의 식사 내역 불러오기\
==> user의 카드 번호 정보 cardnum 변수로 저장\
==> user가 먹은 메뉴 eat_menu 변수로 저장
"""

import pymysql

conn=pymysql.connect(host='capstonedesign.c3lmane8vo1i.ap-northeast-2.rds.amazonaws.com',
                        port=3306,
                        user='admin',
                        password='swusw2022',
                        db='capstonedesign',
                        charset='utf8')
cursor=conn.cursor()
cursor.execute("SELECT * FROM EATMEAL WHERE ChildInfo = '111111111111' AND date_time LIKE '%2022-06-14%';") # 누가, 언제 먹었는지
rows = cursor.fetchall()

cnt = 0
for i in rows:
    print(i)
    globals()["eat_menu{}".format(cnt)] = i[1]
    cnt = cnt + 1

cardnum = rows[0][0]

conn.commit()
conn.close()

"""===> 오늘 먹은 음식 전체 불러오기

2. cardnum 정보를 가지고 CHILD DB에서 childage 정보 불러오기
"""

conn=pymysql.connect(host='capstonedesign.c3lmane8vo1i.ap-northeast-2.rds.amazonaws.com',
                        port=3306,
                        user='admin',
                        password='swusw2022',
                        db='capstonedesign',
                        charset='utf8')
cursor=conn.cursor()
cursor.execute("SELECT * FROM CHILD WHERE CardNum = %s;", (cardnum)) 
(CardNum, ChildName, ChildAge, ChildHeight, ChildWeight, ChildGender) = cursor.fetchone()
print(f"{CardNum},{ChildName},{ChildAge},{ChildHeight},{ChildWeight},{ChildGender}")
childage = ChildAge
conn.commit()
conn.close()

"""3. 식품 영양 정보(FOOD_NUTRITION) DB에서 user가 먹은 eat_menu의 영양 정보를 가져온다."""

conn=pymysql.connect(host='capstonedesign.c3lmane8vo1i.ap-northeast-2.rds.amazonaws.com',
                        port=3306,
                        user='admin',
                        password='swusw2022',
                        db='capstonedesign',
                        charset='utf8')
cursor=conn.cursor()
cursor.execute("SELECT * FROM FOOD_NUTRITION WHERE food_menu = '" + eat_menu0 + "';")
(food_code,food_menu,food_groupname,food_servingsize,food_kcal,food_carbohyd,food_protein,food_fat,food_sugars,food_natrium,food_cholesterol,food_saturatedfatty,food_transfat,Food_Classificaiton) = cursor.fetchone() 
eat_kcal = food_kcal
eat_carbonhyd = food_carbohyd
eat_protein = food_protein
eat_fat = food_fat
eat_natrium = food_natrium
print(f"{food_code},{food_menu},{food_groupname},{food_servingsize},{food_kcal},{food_carbohyd},{food_protein},{food_fat},{food_sugars},{food_natrium},{food_cholesterol},{food_saturatedfatty},{food_transfat}")

conn=pymysql.connect(host='capstonedesign.c3lmane8vo1i.ap-northeast-2.rds.amazonaws.com',
                        port=3306,
                        user='admin',
                        password='swusw2022',
                        db='capstonedesign',
                        charset='utf8')
cursor=conn.cursor()
cursor.execute("SELECT * FROM TEST_FOOD_NUTRITION WHERE food_menu = '" + eat_menu1 + "';")
(food_code,food_menu,food_groupname,food_servingsize,food_kcal,food_carbohyd,food_protein,food_fat,food_sugars,food_natrium,food_cholesterol,food_saturatedfatty,food_transfat,Food_Classificaiton) = cursor.fetchone() 
eat_kcal += food_kcal
eat_carbonhyd += food_carbohyd
eat_protein += food_protein
eat_fat += food_fat
eat_natrium += food_natrium
print(f"{food_code},{food_menu},{food_groupname},{food_servingsize},{food_kcal},{food_carbohyd},{food_protein},{food_fat},{food_sugars},{food_natrium},{food_cholesterol},{food_saturatedfatty},{food_transfat}")
conn.commit()
conn.close()

print("오늘 섭취 칼로리는 %.2f kcal 입니다."%(eat_kcal))
print("오늘 섭취 탄수화물은 %.2f g 입니다."%(eat_carbonhyd))
print("오늘 섭취 단백질은 %.2f g 입니다."%(eat_protein))
print("오늘 섭취 지방은 %.2f g 입니다."%(eat_fat))
print("오늘 섭취 나트륨은 %.2f mg 입니다."%(eat_natrium))

"""4. 받아 온 user의 나이 정보를 바탕으로 연령별 하루 권장 섭취량(RECOMMEND_INTAKE)에서\
 칼로리/탄수화물/단백질/지방/나트륨에 관한 정보 가져와서 부족 영양소 계산하기
"""

conn=pymysql.connect(host='capstonedesign.c3lmane8vo1i.ap-northeast-2.rds.amazonaws.com',
                        port=3306,
                        user='admin',
                        password='swusw2022',
                        db='capstonedesign',
                        charset='utf8')
cursor=conn.cursor()
cursor.execute("SELECT * FROM RECOMMENDED_INTAKE WHERE Child_Age = %s;",(childage))
(Child_Age, food_kcal, food_protein, food_fat, food_carbohyd, food_natrium) = cursor.fetchone() 
print(f"{Child_Age},{food_kcal},{food_carbohyd},{food_protein},{food_fat},{food_natrium}")
lack_kcal = food_kcal - eat_kcal
lack_carbonhyd = food_carbohyd - eat_carbonhyd
lack_protein = food_protein - eat_protein
lack_fat = food_fat - eat_fat
lack_natrium = food_natrium - eat_natrium
conn.commit()
conn.close()

"""5. 부족한 영양소 출력"""

print("오늘 하루 부족한 칼로리는 %.2f kcal 입니다."%(lack_kcal))
print("오늘 하루 부족한 탄수화물은 %.2f g 입니다."%(lack_carbonhyd))
print("오늘 하루 부족한 단백질은 %.2f g 입니다."%(lack_protein))
print("오늘 하루 부족한 지방은 %.2f g 입니다."%(lack_fat))
print("오늘 하루 부족한 나트륨은 %.2f mg 입니다."%(lack_natrium))

"""6. 상단에 부족한 영양소를 확인하면 탄수화물의 경우, 일일 권장량을 초과한 것을 확인할 수 있다. 그러므로 탄수화물이 적고 지방과 단백질 보충이 가능한 음식을 추천하려 한다."""

conn=pymysql.connect(host='capstonedesign.c3lmane8vo1i.ap-northeast-2.rds.amazonaws.com',
                        port=3306,
                        user='admin',
                        password='swusw2022',
                        db='capstonedesign',
                        charset='utf8')
cursor=conn.cursor()
cursor.execute("SELECT * FROM TEST_FOOD_NUTRITION WHERE food_carbohyd < 10 AND food_menu != '햄버거';") #햄버거 영양소 데이터가 다 0으로 이상함,,
(food_code,food_menu,food_groupname,food_servingsize,food_kcal,food_carbohyd,food_protein,food_fat,food_sugars,food_natrium,food_cholesterol,food_saturatedfatty,food_transfat,Food_Classificaiton) = cursor.fetchone() 
recommend_food = food_menu
print(f"{food_code},{food_menu},{food_groupname},{food_servingsize},{food_kcal},{food_carbohyd},{food_protein},{food_fat},{food_sugars},{food_natrium},{food_cholesterol},{food_saturatedfatty},{food_transfat}")
conn.commit()
conn.close()

"""갈비탕을 추천했다.
해당 메뉴를 파는 가게를 추천
"""

conn=pymysql.connect(host='capstonedesign.c3lmane8vo1i.ap-northeast-2.rds.amazonaws.com',
                        port=3306,
                        user='admin',
                        password='swusw2022',
                        db='capstonedesign',
                        charset='utf8')
cursor=conn.cursor()
cursor.execute("SELECT * FROM capstonedesign.TEST_STORELIST WHERE Store_Classification = '한식' AND store_name LIKE '%갈비탕%';")
(store_num,store_name,store_address,Store_Classification,X,Y) = cursor.fetchone() 
recommend_food = food_menu
print(f"{store_num},{store_name},{store_address},{Store_Classification},{X},{Y}")
conn.commit()
conn.close()